wip

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,22 +1,35 @@
-FROM ubuntu:24.04
+ARG VARIANT="noble"
+FROM buildpack-deps:${VARIANT}-curl
 
-ENV DEBIAN_FRONTEND=noninteractive
-ENV PYTHONUNBUFFERED=1
+LABEL dev.containers.features="common"
 
-# System Dependencies
-RUN apt-get update && apt-get install -y --no-install-recommends \
-    python3 \
-    python3-venv \
-    python3-pip \
-    curl \
-    jq \
-    git \
-    uuid-runtime \
-    openssh-client \
-    ca-certificates \
+ARG VARIANT
+RUN if [ "$VARIANT" = "noble" ]; then \
+        if id "ubuntu" &>/dev/null; then \
+            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+        else \
+            echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+        fi; \
+    fi
+
+# [Optional] Uncomment this section to install additional OS packages.
+# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
+#     && apt-get -y install --no-install-recommends <your-package-list-here>
+
+# Local fix for issue with timezone data at 'buildpack-deps'. Ref# https://github.com/devcontainers/images/issues/1709
+RUN apt-get update \
+    && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -y reinstall --no-install-recommends tzdata \
+												    python3 \
+												    python3-venv \
+												    python3-pip \
+												    curl \
+												    jq \
+												    git \
+												    uuid-runtime \
+												    openssh-client \
+												    ca-certificates \    
     && rm -rf /var/lib/apt/lists/*
-
-WORKDIR /workspace
 
 # -------------------------
 # Jupyter Base
@@ -54,4 +67,5 @@ RUN python3 -m venv /opt/mcp \
  && /opt/mcp/bin/python -m ipykernel install \
       --sys-prefix --name=mcp --display-name="Python (mcp)"
 
+WORKDIR /workspace
 RUN curl -L https://github.com/mc-b/lernvirt/archive/refs/heads/main.tar.gz | tar xz --strip-components=3 lernvirt-main/examples/aiaas --exclude='*/'
